# -*- coding: utf-8 -*-
#
# Copyright (C) 2019 Esteban J. Garcia Gabancho.
#
# Invenio-SAML is free software; you can redistribute it and/or modify it
# under the terms of the MIT License; see LICENSE file for more details.

notifications:
  email: false

sudo: false

language: python

services:
  - mysql
  - postgresql
  - redis

cache:
  - pip

env:
  - REQUIREMENTS=lowest EXTRAS=all,sqlite SQLALCHEMY_DATABASE_URI="sqlite:///test.db"
  - REQUIREMENTS=lowest EXTRAS=all,mysql SQLALCHEMY_DATABASE_URI="mysql+pymysql://root@localhost:3306/invenio"
  - REQUIREMENTS=lowest EXTRAS=all,postgresql SQLALCHEMY_DATABASE_URI="postgresql+psycopg2://postgres@localhost:5432/invenio"
  - REQUIREMENTS=release EXTRAS=all,sqlite SQLALCHEMY_DATABASE_URI="sqlite:///test.db"
  - REQUIREMENTS=release EXTRAS=all,mysql SQLALCHEMY_DATABASE_URI="mysql+pymysql://root@localhost:3306/invenio"
  - REQUIREMENTS=release EXTRAS=all,postgresql SQLALCHEMY_DATABASE_URI="postgresql+psycopg2://postgres@localhost:5432/invenio" DEPLOY=true
  - REQUIREMENTS=devel EXTRAS=all,sqlite SQLALCHEMY_DATABASE_URI="sqlite:///test.db"
  - REQUIREMENTS=devel EXTRAS=all,mysql SQLALCHEMY_DATABASE_URI="mysql+pymysql://root@localhost:3306/invenio"
  - REQUIREMENTS=devel EXTRAS=all,postgresql SQLALCHEMY_DATABASE_URI="postgresql+psycopg2://postgres@localhost:5432/invenio"

matrix:
  fast_finish: true
  allow_failures:
    - env: REQUIREMENTS=devel EXTRAS=all,sqlite SQLALCHEMY_DATABASE_URI="sqlite:///test.db"
    - env: REQUIREMENTS=devel EXTRAS=all,mysql SQLALCHEMY_DATABASE_URI="mysql+pymysql://root@localhost:3306/invenio"
    - env: REQUIREMENTS=devel EXTRAS=all,postgresql SQLALCHEMY_DATABASE_URI="postgresql+psycopg2://postgres@localhost:5432/invenio"

python:
  - "3.6"
  - "3.7"

before_install:
  - "sudo apt-get install -y libxml2-dev libxmlsec1-dev"
  - "travis_retry pip install wtforms['email']"
  - "travis_retry pip install --upgrade pip setuptools py"
  - "travis_retry pip install twine wheel coveralls requirements-builder"
  - "requirements-builder -e all --level=min setup.py > .travis-lowest-requirements.txt"
  - "requirements-builder -e all --level=pypi setup.py > .travis-release-requirements.txt"
  - "requirements-builder -e all --level=dev --req requirements-devel.txt setup.py > .travis-devel-requirements.txt"

install:
  - "travis_retry pip install -r .travis-${REQUIREMENTS}-requirements.txt"
  - "travis_retry pip install -e .[${EXTRAS}]"

script:
  - "./run-tests.sh"

after_success:
  - coveralls

deploy:
  distributions: compile_catalog sdist bdist_wheel
  "on":
    condition: $DEPLOY = true
    python: "3.7"
    repo: inveniosoftware/invenio-saml
    tags: true
  password:
    secure: jqv2KwlBqo7j7d1AEgrGRdc11fqkj1VC6CH6kyChSgEjOvz1UPJW9cfN26qpag9u4s6QMpGMowqDuzLQuSGx6CN2rjWsocflgihO/Ob3R2NlFLzD3NIgjLPhP0NMVCqgrK/s+3CV4RDap2cDA9cvTRLf4URjIKxZY1mAL5R5sXSnurX0ZouWhFm3R+EFoNKDqDp3lFPrM6SpR/f6LKYpbTSr0C7Vm7bTYX6zL9BaQa/K4ai2VqLYd3ZxEek/J6p0PDHw0jufgjctSfurFXObWcwPb+7g55J8GBEV3ugR+nGcFztV1OYyhnjKcgmfGdcSaweH7fFQDPVLeZJY0ZWxTCWhxh6glnzQWW5mylS0ksgIYLbey3cosXHzTnAFoFmBCsThDwJ132x503i71XZWOLJPfr8onZqXWStuAyM2+XMXIBCQUAou0bNzsjN5mbhYLeTLkxipVn4Zy6z/eV3qMXGuX43xmcBveaLPiQp76aHxUKh00DgnxKEjmGSwXeLqkAPcWiT4zVdEHFn5KYYduj4NZ6M00mpQE6Y4oJnYN5vfnanwacBlFKxwDcB/fGRKRsNV3XU4esYPTOA+LYrL3nj3J1EDqMN0KyoQMa/4vD6H4gtfCdai7/s6cS+kN1z0U/AwQeWF2EV6Wf10VVTeVBQk9fBkG/Npz+8HgP1CxCk=
  provider: pypi
  user: inveniosoftware
